version: '2'
services:
    matv53-app:
        image: matv53
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://matv53-postgresql:5432/matv53
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=matv53-elasticsearch:9300
        ports:
            - 8080:8080
    matv53-postgresql:
        extends:
            file: postgresql.yml
            service: matv53-postgresql
    matv53-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: matv53-elasticsearch
